/*
Business question:
How much revenue is generated by each customer acquisition cohort?

Business purpose:
Groups customers by first-purchase month and measures cohort value.

Logic:
Uses dim_customer cohort_month and fact revenue.
*/

SELECT
  cohort_month,
  COUNT(DISTINCT customer_id) AS cohort_customers,
  ROUND(SUM(CASE WHEN NOT is_cancelled THEN gross_revenue ELSE 0 END), 2)
    AS total_revenue_to_date,
  ROUND(
    SAFE_DIVIDE(
      SUM(CASE WHEN NOT is_cancelled THEN gross_revenue ELSE 0 END),
      COUNT(DISTINCT customer_id)),
    2)
    AS revenue_per_customer
FROM `project-f57ec015-00f5-4842-84d.online_retail_bi.vw_sales_analytics`
WHERE customer_id IS NOT NULL
GROUP BY cohort_month
ORDER BY cohort_month;

